fszlin/certes

docs/README.md
docs : fixed readme to include "how to" use the DNS Challenge.
fix : replaced the "Where().. First()" with a simple call to First() on getting the challenge
=> docs : fixed readme to include "how to" use the DNS Challenge. (Ref issue #2)

test/Certes.Tests.Integration/IntegrationHelper.cs
update local boulder URL with lo0.in host name, so we may use a proper SSL for testing.
=> update hostname for local boulder

docs/README.md, docs/README.v2.md
pin ci badges to master branch
=> pin ci badges to master branch

appveyor.yml, codecov.yml
Update codecov settings with flags
=> setup codecov flags

.bettercodehub.yml, Certes.sln
=> add config for analysis

docs/README.v2.md
=> add bch badge

src/Certes.Cli/Commands/AccountNewCommand.cs, src/Certes.Cli/Commands/CertificateCommand.cs, src/Certes.Cli/Commands/CertificatePemCommand.cs, src/Certes.Cli/Commands/CertificatePfxCommand.cs, src/Certes.Cli/Commands/CommandBase.cs, src/Certes.Cli/Commands/CommandGroup.cs, src/Certes.Cli/Commands/OrderFinalizeCommand.cs, src/Certes.Cli/Commands/OrderNewCommand.cs, src/Certes.Cli/Strings.Designer.cs, src/Certes.Cli/Strings.resx, src/Certes/Acme/CertificateChain.cs, src/Certes/Acme/CertificateContent.cs, src/Certes/Extensions/CertificateChainExtensions.cs, src/Certes/Extensions/CertificateInfo.cs, src/Certes/IEncodable.cs, src/Certes/IKey.cs, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByHttpTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.cs, test/Certes.Tests/Cli/AcmeContextFactoryTests.cs, test/Certes.Tests/Cli/Commands/AccountShowCommandTests.cs, test/Certes.Tests/Cli/Commands/CertificatePemCommandTests.cs, test/Certes.Tests/Cli/Commands/CertificatePfxCommandTests.cs, test/Certes.Tests/Cli/Commands/OrderFinalizeCommandTests.cs, test/Certes.Tests/IOrderContextExtensionsTests.cs
=> [cli] add cert commands

appveyor.yml, codecov.yml, test/Certes.Tests/Pkcs/PfxBuilderTests.cs
=> update test config

src/Certes/Acme/ChallengeContext.cs, src/Certes/Acme/Resource/AuthorizationStatus.cs, src/Certes/Acme/Resource/ChallengeStatus.cs, src/Certes/Acme/Resource/OrderStatus.cs, test/Certes.Tests/Acme/Resource/AuthorizationTests.cs
updates for [draft-10](https://tools.ietf.org/html/draft-ietf-acme-acme-10)
=> updates for draft-10

docs/CHANGELOG.md, docs/README.md
=> v2 release

appveyor.yml, src/Certes.Cli/Certes.Cli.csproj, src/Certes/Certes.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj
=> fix tag names

appveyor.yml, docs/CHANGELOG.md, src/Certes/Certes.csproj
=> update pkg version

docs/CHANGELOG.md, docs/README.md, src/Certes.Cli/Commands/AzureCommand.cs, src/Certes.Cli/Commands/AzureSetCommand.cs, src/Certes.Cli/Settings/AzureSettings.cs, src/Certes.Cli/Settings/UserSettings.cs, src/Certes.Cli/Strings.Designer.cs, src/Certes.Cli/Strings.resx, src/Certes/Extensions/IOrderContextExtensions.cs, test/Certes.Tests/Cli/Commands/AzureAppCommandTests.cs, test/Certes.Tests/Cli/Commands/AzureDnsCommandTests.cs, test/Certes.Tests/Cli/Commands/AzureSetCommandTests.cs, test/Certes.Tests/Cli/Settings/UserSettingsTests.cs
=> Fix CLI parameter name

appveyor.yml, src/Certes.Cli/Certes.Cli.csproj, src/Certes.Cli/Commands/CertificatePemCommand.cs, src/Certes/Certes.csproj, test/Certes.Tests/Cli/Commands/CertificatePemCommandTests.cs
=> update cli for dotnet 2.1 p2

src/Certes.Cli/Settings/UserSettings.cs, test/Certes.Tests/Cli/Settings/UserSettingsTests.cs
fix cli env var name  CERTES_AZURE_TENANT_ID
=> fix cli env var name

src/Certes/Pkcs/PfxBuilder.cs, test/Certes.Tests.Integration/AcmeContextIntegration.WildcardTests.cs
* build pfx cert chain using BC store
#100
=> fix certificate chain for pfx

.appveyor.yml, docs/CHANGELOG.md, src/Certes/Certes.csproj
* Update nupkg version to v2.2.0
* Mark Challenge.KeyAuthorization obsolete
=> v2.2.0 release

src/Certes/Acme/Resource/Challenge.cs
mark Challenge.KeyAuthorization obsolete
=> mark Challenge.KeyAuthorization obsolete

.appveyor.yml, src/Certes/Certes.csproj
* update SDK to netcore 2.1 rc1
* bump version for dev
=> Update SDK to netcore 2.1 rc1

test/Certes.Tests/Cli/Commands/AzureAppCommandTests.cs, test/Certes.Tests/Cli/Commands/CertificatePfxCommandTests.cs, test/Certes.Tests/Helper.cs, test/Certes.Tests/Pkcs/PfxBuilderTests.cs
* load test certifcate from lo0.in
=> Fix expired test certificates

.appveyor.yml, .travis.yml, src/Certes.Cli/Certes.Cli.csproj, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByDnsTests.cs, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests/Certes.Tests.csproj
* update build scripts
* update nupkg
=> update sdk to v2.1

.appveyor.yml, docs/CHANGELOG.md, src/Certes.Cli/Certes.Cli.csproj, src/Certes/Certes.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj
* bump certes to 2.2.3
* bump cli to 1.0.2
=> increase dev version

.travis.yml, test/Certes.Tests.Integration/AcmeContextIntegration.cs, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests.Web/Startup.cs, test/Certes.Tests/Helper.cs
=> Update test for order ready status

docs/README.md
Corrected the command that installs Certes CLI
=> corrected the command that installs Certes CLI

.appveyor.yml, docs/APIv2.md, docs/CHANGELOG.md, src/Certes/Acme/Resource/ChallengeTypes.cs, src/Certes/Certes.csproj, src/Certes/Extensions/IAuthorizationContextExtensions.cs, src/Certes/IKey.cs, src/Certes/Pkcs/PfxBuilder.cs, test/Certes.Tests.Integration/AcmeContextIntegration.AccountFlowTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByHttpTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByTlsAlpnTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.ChangeAccountTests.cs, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Integration/IntegrationHelper.cs, test/Certes.Tests/Certes.Tests.csproj, test/Certes.Tests/IAuthorizationContextExtensionsTests.cs, test/scripts/tls-alpn-responder.go
* add tls-alpn-01 challenge type
=> [wip] support tls-alpn-01

docs/CHANGELOG.md, src/Certes/Acme/AcmeHttpHandler.cs, src/Certes/Acme/EntityContext.cs, src/Certes/Acme/IAcmeHttpClient.cs, src/Certes/AcmeClient.cs, src/Certes/AcmeRequestException.cs, test/Certes.Tests/AcmeClientTests.cs, test/Certes.Tests/AcmeRequestExceptionTests.cs
- use ACME error details as exception message
#109
=> Improve error handling

.appveyor.yml, src/Certes/Certes.csproj, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByDnsTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByHttpTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.cs
* update version to 2.31.
* update tests to counter az func cold start
=> bump dev ver

docs/CLI.md, docs/README.md, docs/api/toc.yml, docs/api/topics/toc.yml, test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByHttpTests.cs, test/Certes.Tests.Integration/AcmeContextIntegration.cs
=> Add CLI doc

docs/README.md
Adding missing awaits in README.md
=> README.md - Add missing awaits

docs/CHANGELOG.md, src/Certes.Cli/Commands/CertificatePfxCommand.cs, src/Certes.Cli/Strings.Designer.cs, src/Certes.Cli/Strings.resx, test/Certes.Tests/Cli/Commands/CertificatePfxCommandTests.cs
=> [CLI] add `--issuer` option for exporting PFX

.travis.yml, docs/CHANGELOG.md, src/Certes.Cli/Certes.Cli.csproj, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests/Certes.Tests.csproj
=> Update CLI version

src/Certes.Cli/Certes.Cli.csproj, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests/Certes.Tests.csproj
=> Bump CLI version

.appveyor.yml, src/Certes/Certes.csproj, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests.Web/host.json, test/Certes.Tests/Certes.Tests.csproj
Update System.Net.Http reference
#158
=> fix System.Net.Http reference for desktop netfx

docs/CHANGELOG.md, src/Certes/AcmeContext.cs
Update payload for Account Key Roll-over according to draft-13
#154
=> fix key rollover error

docs/CHANGELOG.md, src/Certes/IKey.cs
=> Update TLS-ALPN OID

.travis.yml, src/Certes.Cli/Certes.Cli.csproj, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests.Web/CertificateFunction.cs, test/Certes.Tests.Web/DnsChanllengeFunction.cs, test/Certes.Tests.Web/HttpChanllengeFunction.cs, test/Certes.Tests/Certes.Tests.csproj, test/Certes.Tests/Cli/Commands/AzureAppCommandTests.cs
=> update supporting packages

.appveyor.yml
=> update version to 2.3.2

src/Certes/Certes.csproj
=> update package version

.appveyor.yml, docs/CHANGELOG.md, src/Certes/Certes.csproj
=> update version to 2.3.3

docs/CHANGELOG.md, src/Certes/Acme/AccountContext.cs, src/Certes/Acme/EntityContext.cs, src/Certes/Acme/OrderContext.cs, src/Certes/Jws/JwsSigner.cs, test/Certes.Tests/Acme/AccountContextTests.cs, test/Certes.Tests/Acme/AuthorizationContextTests.cs, test/Certes.Tests/Acme/EntityContextTests.cs, test/Certes.Tests/Acme/OrderContextTests.cs
Implement `POST-as-GET` for loading ACME resources
=> Implement POST-as-GET

.github/stale.yml, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests/Certes.Tests.csproj
=> update xunit packages

.travis.yml, docs/CHANGELOG.md, src/Certes.Cli/Certes.Cli.csproj, src/Certes/Json/JsonUtil.cs, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests/Certes.Tests.csproj
=> release v2.3.3

docs/APIv2.md
fix #185
fix API doc for Order
=> fix #185 - incorrect API doc for Order

src/Certes.Cli/Commands/OrderAuthzCommand.cs, test/Certes.Tests/Cli/Commands/OrderAuthzCommandTests.cs
Issue #208
Add the challenge information that need to be placed in the files for the http challenge.
=> Return http challenge data

.appveyor.yml, .travis.yml, Certes.sln, azure-pipelines.yml, docs/CHANGELOG.md, scripts/build.yml, src/Certes.Cli/Certes.Cli.csproj, src/Certes/Certes.csproj, src/Certes/Pkcs/CertificationRequestBuilder.cs, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Integration/IntegrationHelper.cs, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests/AcmeClientTests.cs, test/Certes.Tests/Certes.Tests.csproj, test/scripts/tls-alpn-responder.go
- Remove support for netstandard1.3
- Upgrade CLI to netcoreapp3.1
- Upgrade Azure Functions runtime
=> Update target frameworks

src/Certes.Cli/Commands/OrderFinalizeCommand.cs, src/Certes.Cli/Strings.Designer.cs, src/Certes.Cli/Strings.resx, test/Certes.Tests/Cli/Commands/OrderFinalizeCommandTests.cs
=> Add options for algorithm in order finalize method

docs/CHANGELOG.md
=> update change log for v2.3.4

src/Certes.Cli/AzureClientFactory.cs, src/Certes.Cli/Certes.Cli.csproj, src/Certes.Cli/Commands/AzureAppCommand.cs, src/Certes.Cli/Commands/AzureCommand.cs, src/Certes.Cli/Commands/AzureDnsCommand.cs, src/Certes.Cli/Commands/AzureSetCommand.cs
=> update cli dependencies

src/Certes.Cli/Commands/AzureAppCommand.cs, src/Certes.Cli/Commands/AzureDnsCommand.cs, src/Certes.Cli/Commands/AzureSetCommand.cs
CLI - set subscription ID for Azure clients.
=> set az client subscription id

src/Certes/Acme/AccountContext.cs
Fix the selection of correct HMAC hashing algorithm for external account binding.
Thanks for contributing!
=> Fix EAB HMAC selection

GitVersion.yml, src/Certes/Acme/AcmeHttpClient.cs, test/Certes.Tests/Acme/AcmeHttpClientTests.cs
Bump version to v3.
Thanks for contributing!
=> Bump version to v3

GitVersion.yml, scripts/pack.yml
update git version settings.
Thanks for contributing!
=> update git version settings

GitVersion.yml, azure-pipelines.yml, misc/certes.props, src/Certes.Cli/Certes.Cli.csproj, src/Certes.Cli/Commands/AzureDnsCommand.cs, test/Certes.Tests.Integration/Certes.Tests.Integration.csproj, test/Certes.Tests.Web/Certes.Tests.Web.csproj, test/Certes.Tests/Certes.Tests.csproj
Please describe the purpose of the pull request.
Thanks for contributing!
=> Remove netcoreapp2.1 tests
